### ISSUE TITLE
problem with the d.ts files

### ISSUE THREAD

**Issue by CarlosOnline** [kristianmandrup/aurelia-definitely-typed#1]
There is a trailing ] at the end of many variables.

For example: viewUrl] in typings\aurelia\aurelia.d.ts

```
class ViewResources {
    public viewUrl];
}
```

**Comment by kristianmandrup** [comment]
Yup, do a global replace of `];` with `: string;`. Was a find/replace error that I was unable to undo in Atom editor :P Thanks. But will also replace some valid cases. Damn! Re-copy/paste the original `d.ts` files from @cmichael then...
@CarlosOnline you are most welcome to help out ;)

**Comment by kristianmandrup** [comment]
re-copied all the `d.ts` files from: 

https://github.com/cmichaelgraham/aurelia-typescript/tree/master/master/typings
